version: '3.7'

networks:
  nginx:
    name: nginx
    external: true

services:
  nocodb-wrapper:
    image: keyruu/nocodb-wrapper:latest
    container_name: nocodb-wrapper
    restart: always

    networks:
      - nginx

    environment:
      NOCODB_API_TOKEN: token
      NOCODB_API_URL: url
